# Generated by Django 6.0.6 on 2026-06-21 12:38

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('admin_staff', 'Admin Staff'), ('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('salesperson', 'Salesperson')], help_text='Determines which app this user can access and what they can do. Admin / Admin Staff → platform (no company). Owner / Manager / Cashier / Salesperson → client POS (must have a company).', max_length=20, verbose_name='Role')),
                ('email', models.EmailField(help_text='Used as the login credential. Must be unique across the entire platform.', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='ACTIVE → can log in. INACTIVE → disabled by owner/admin (staff left, etc.). SUSPENDED → disabled by platform Admin only (non-payment, breach). Owner cannot lift a suspension — only platform Admin can.', max_length=20, verbose_name='Account Status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(blank=True, help_text='NULL for Admin and Admin Staff (platform users). Required for Owner, Manager, Cashier, Salesperson.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this account. NULL for the very first Admin (created via manage.py createsuperuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['company', 'role'], name='user_company_role_idx'), models.Index(fields=['status'], name='user_status_idx'), models.Index(fields=['role'], name='user_role_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('company',), name='unique_owner_per_company'), models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['admin', 'admin_staff']), _negated=True), ('company__isnull', True), _connector='OR'), name='platform_users_have_no_company'), models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['owner', 'manager', 'cashier', 'salesperson']), _negated=True), ('company__isnull', False), _connector='OR'), name='client_users_must_have_company')],
            },
        ),
    ]
