# Generated by Django 6.0.6 on 2026-06-23 08:11

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.user_profile_upload_path, verbose_name='Profile Image'),
        ),
    ]
