# Generated by Django 6.0.6 on 2026-06-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_fbr_production_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_logs', to='companies.company')),
            ],
            options={
                'verbose_name': 'Scenario Test Log',
                'verbose_name_plural': 'Scenario Test Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
