# Generated by Django 6.0.6 on 2026-06-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auditlog'),
        ('digital_invoicing', '0001_initial'),
        ('pos', '0012_alter_sale_fbr_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBRSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('endpoint', models.CharField(max_length=50)),
                ('local_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fbr_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbr_submissions', to='companies.company')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbr_submissions', to='pos.sale')),
            ],
            options={
                'verbose_name': 'FBR Submission Log',
                'verbose_name_plural': 'FBR Submission Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='digital_inv_company_0d911c_idx'), models.Index(fields=['local_invoice_id'], name='digital_inv_local_i_750d63_idx')],
            },
        ),
    ]
