# Generated by Django 6.0.6 on 2026-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0002_fbrsubmissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbrsubmissionlog',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbrsubmissionlog',
            name='response_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
