# Generated by Django 6.0.6 on 2026-06-22 10:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_fbr_assigned_scenarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Maps to 'productDescription' in FBR invoice JSON.", max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text="Base selling price excluding sales tax. Maps to 'valueSalesExcludingST' in FBR JSON. Tax is calculated on top of this at sale time.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price (excl. tax)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Purchase/cost price. Used for profit margin reporting. Not sent to FBR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Price')),
                ('barcode', models.CharField(blank=True, help_text='Optional. Supports EAN-13, UPC-A, Code 128, QR, etc. Used by barcode scanner on POS terminal.', max_length=100, verbose_name='Barcode')),
                ('sku', models.CharField(blank=True, help_text='Internal stock keeping unit code. Optional but recommended.', max_length=100, verbose_name='SKU')),
                ('unit_of_measure', models.CharField(choices=[('Numbers, pieces, units', 'Numbers / Pieces / Units'), ('KG', 'Kilogram (KG)'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('ML', 'Millilitre (ML)'), ('Metre', 'Metre'), ('Square Metre', 'Square Metre'), ('KWH', 'Kilowatt Hour (KWH)'), ('Ton', 'Ton'), ('Dozen', 'Dozen'), ('Pack', 'Pack'), ('Box', 'Box'), ('Set', 'Set')], default='Numbers, pieces, units', help_text="Maps to 'uoM' in FBR invoice JSON. Must match FBR reference values from /pdi/v1/uom.", max_length=50, verbose_name='Unit of Measure (UoM)')),
                ('hs_code', models.CharField(blank=True, help_text="Harmonized System code. REQUIRED by FBR for manufacturer-cum-retailer. Format: XXXX.XXXX (e.g. 0101.2100). Maps to 'hsCode' in FBR invoice JSON.", max_length=20, verbose_name='HS Code')),
                ('fbr_sale_type', models.CharField(choices=[('Goods at standard rate (default)', 'Standard Rate (Default)'), ('Goods at Reduced Rate', 'Goods at Reduced Rate'), ('Exempt Goods', 'Exempt Goods'), ('Goods at zero-rate', 'Zero Rated Goods'), ('3rd Schedule Goods', '3rd Schedule Goods'), ('Steel Melting and re-rolling', 'Steel Melting & Re-rolling'), ('Ship breaking', 'Ship Breaking'), ('Cotton Ginners', 'Cotton Ginners'), ('Telecommunication services', 'Telecommunication Services'), ('Toll Manufacturing', 'Toll Manufacturing'), ('Petroleum Products', 'Petroleum Products'), ('Electricity Supply to Retailers', 'Electricity Supply to Retailers'), ('Gas to CNG stations', 'Gas to CNG Stations'), ('Mobile Phones', 'Mobile Phones'), ('Processing/ Conversion of Goods', 'Processing / Conversion of Goods'), ('Goods (FED in ST Mode)', 'Goods — FED in ST Mode'), ('Services (FED in ST Mode)', 'Services — FED in ST Mode'), ('Services', 'Services'), ('Electric Vehicle', 'Electric Vehicle'), ('Cement /Concrete Block', 'Cement / Concrete Block'), ('Potassium Chlorate', 'Potassium Chlorate'), ('CNG Sales', 'CNG Sales'), ('Goods as per SRO.297(|)/2023', 'Goods per SRO 297(I)/2023'), ('Non-Adjustable Supplies', 'Non-Adjustable Supplies (Drugs)')], default='Goods at standard rate (default)', help_text="Determines which tax rules apply. Maps to 'saleType' in FBR invoice JSON. Must match exactly the string FBR expects.", max_length=80, verbose_name='FBR Sale Type')),
                ('tax_rate_percent', models.CharField(choices=[('0%', '0% — Zero Rated / Exempt'), ('1%', '1%'), ('2%', '2%'), ('3%', '3%'), ('5%', '5%'), ('8%', '8%'), ('10%', '10%'), ('12%', '12%'), ('13%', '13%'), ('15%', '15%'), ('17%', '17%'), ('18%', '18% — Standard Rate'), ('20%', '20%'), ('25%', '25%')], default='18%', help_text="Sales tax rate. Maps to 'rate' in FBR invoice JSON. Use 0% for exempt or zero-rated goods.", max_length=10, verbose_name='Tax Rate')),
                ('fbr_fixed_retail_price', models.DecimalField(decimal_places=2, default=0, help_text="For 3rd schedule goods with a fixed retail price. Maps to 'fixedNotifiedValueOrRetailPrice' in FBR JSON. Leave 0 for most products.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fixed / Notified Value or Retail Price')),
                ('fbr_sales_tax_withheld', models.DecimalField(decimal_places=2, default=0, help_text="For withholding agent scenarios. Maps to 'salesTaxWithheldAtSource' in FBR JSON. Leave 0 for normal retail sales.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sales Tax Withheld at Source')),
                ('fbr_further_tax', models.DecimalField(decimal_places=2, default=0, help_text="Additional tax on sales to unregistered buyers (where applicable). Maps to 'furtherTax' in FBR JSON.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Further Tax')),
                ('fbr_extra_tax', models.DecimalField(decimal_places=2, default=0, help_text="Applicable for certain sectors (e.g. steel, petroleum). Maps to 'extraTax' in FBR JSON. Leave 0 for most products.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extra Tax')),
                ('fbr_fed_payable', models.DecimalField(decimal_places=2, default=0, help_text="Federal excise duty. Applicable for specific goods (tobacco, beverages, etc.). Maps to 'fedPayable' in FBR JSON.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Federal Excise Duty (FED) Payable')),
                ('fbr_default_discount', models.DecimalField(decimal_places=2, default=0, help_text="Default per-item discount amount. Can be overridden at sale time. Maps to 'discount' in FBR JSON.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Default Discount')),
                ('fbr_sro_schedule_no', models.CharField(blank=True, help_text="Statutory Regulatory Order schedule number. Required for SRO-based sale types (SN024, SN025). Maps to 'sroScheduleNo' in FBR JSON.", max_length=50, verbose_name='SRO Schedule No.')),
                ('fbr_sro_item_serial_no', models.CharField(blank=True, help_text="Item serial number within the SRO schedule. Maps to 'sroItemSerialNo' in FBR JSON.", max_length=20, verbose_name='SRO Item Serial No.')),
                ('track_inventory', models.BooleanField(default=False, help_text='If True, stock level is tracked and decremented on each sale. Only meaningful if company has module_inventory=True.', verbose_name='Track Inventory')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, help_text='Current stock quantity. Decremented by sales, incremented by stock-ins. Only tracked if track_inventory=True.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Stock')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, help_text='Alert when current_stock falls below this value. Set to 0 to disable low-stock alerts.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Low Stock Threshold')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products do not appear in the POS product search.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.category', verbose_name='Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='product_company_active_idx'), models.Index(fields=['barcode'], name='product_barcode_idx'), models.Index(fields=['sku'], name='product_sku_idx'), models.Index(fields=['hs_code'], name='product_hs_code_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('barcode__gt', '')), fields=('company', 'barcode'), name='unique_barcode_per_company'), models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('company', 'sku'), name='unique_sku_per_company')],
            },
        ),
    ]
