# Generated by Django 6.0.6 on 2026-06-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_fbr_assigned_scenarios_and_more'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the individual or registered business name. Maps to 'buyerBusinessName' in FBR invoice JSON.", max_length=255, verbose_name='Customer Name / Business Name')),
                ('ntn_cnic', models.CharField(blank=True, help_text="National Tax Number (7 or 9 digits) for registered businesses, or CNIC (13 digits) for individuals. REQUIRED for FBR registered buyer scenarios (SN001, SN005). Maps to 'buyerNTNCNIC' in FBR invoice JSON.", max_length=15, verbose_name='NTN / CNIC')),
                ('registration_type', models.CharField(choices=[('Registered', 'Registered (NTN holder)'), ('Unregistered', 'Unregistered')], default='Unregistered', help_text="Registered = NTN holder who can claim input tax credit. Unregistered = individual or non-registered business. Maps to 'buyerRegistrationType' in FBR invoice JSON.", max_length=15, verbose_name='Registration Type')),
                ('province', models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa (KPK)'), ('Balochistan', 'Balochistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad', 'Islamabad Capital Territory')], help_text="Customer's province. Maps to 'buyerProvince' in FBR invoice JSON.", max_length=50, verbose_name='Province')),
                ('address', models.TextField(blank=True, help_text="Full business or home address. Maps to 'buyerAddress' in FBR invoice JSON.", verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('is_walk_in', models.BooleanField(default=False, help_text='If True this is the shared anonymous walk-in record for this company. Used for cash sales where customer details are not collected. Each company has exactly one walk-in record. Cannot be deleted.', verbose_name='Walk-In Customer')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive customers do not appear in POS customer search.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(help_text='Every customer belongs to exactly one company (tenant).', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='customer_company_active_idx'), models.Index(fields=['ntn_cnic'], name='customer_ntn_cnic_idx'), models.Index(fields=['registration_type'], name='customer_reg_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_walk_in', True)), fields=('company',), name='unique_walkin_per_company'), models.UniqueConstraint(condition=models.Q(('ntn_cnic__gt', '')), fields=('company', 'ntn_cnic'), name='unique_ntn_cnic_per_company')],
            },
        ),
    ]
