# Generated by Django 6.0.6 on 2026-06-22 11:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_fbr_assigned_scenarios_and_more'),
        ('pos', '0002_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10, verbose_name='Status')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Cash in the till at the start of the shift.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Opening Cash Balance')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened At')),
                ('opening_note', models.TextField(blank=True, verbose_name='Opening Note')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash counted in the till at end of shift.', max_digits=12, null=True, verbose_name='Closing Cash Count')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='System-calculated: opening_balance + total cash sales during session. Computed when session is closed.', max_digits=12, null=True, verbose_name='Expected Cash')),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, help_text='closing_balance − expected_cash. Negative = shortage.', max_digits=12, null=True, verbose_name='Cash Difference')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('closing_note', models.TextField(blank=True, verbose_name='Closing Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(help_text='The user who opened this session.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Cash Session',
                'verbose_name_plural': 'Cash Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(help_text='Our internal sequential invoice number. Format: INV-YYYY-NNNNNN (e.g. INV-2025-000001). Auto-generated on save.', max_length=50, unique=True, verbose_name='Sale / Invoice Number')),
                ('sale_type', models.CharField(choices=[('Sale Invoice', 'Sale Invoice'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], default='Sale Invoice', help_text="Maps to 'invoiceType' in FBR invoice JSON.", max_length=20, verbose_name='Sale Type')),
                ('status', models.CharField(choices=[('draft', 'Draft / On Hold'), ('completed', 'Completed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=15, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of (selling_price × quantity) for all lines.', max_digits=14, verbose_name='Subtotal (excl. tax)')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of discount amounts across all lines.', max_digits=14, verbose_name='Total Discount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, help_text='Sum of salesTaxApplicable across all lines.', max_digits=14, verbose_name='Total Sales Tax')),
                ('total_further_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Further Tax')),
                ('total_fed', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total FED Payable')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text="Grand total the customer pays. Maps to sum of 'totalValues' across all FBR line items.", max_digits=14, verbose_name='Total Amount (incl. all taxes)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all SalePayment rows. Must equal total_amount on completion.', max_digits=14, verbose_name='Amount Paid')),
                ('change_given', models.DecimalField(decimal_places=2, default=0, help_text='Cash change returned to customer (amount_paid − total_amount).', max_digits=14, verbose_name='Change Given')),
                ('fbr_submission_status', models.CharField(choices=[('pending', 'Pending — not yet submitted to FBR'), ('success', 'Submitted & Validated by FBR'), ('failed', 'Submission Failed'), ('skipped', 'Skipped — FBR DI not enabled for this company')], default='pending', max_length=10, verbose_name='FBR Submission Status')),
                ('fbr_invoice_number', models.CharField(blank=True, help_text="Assigned by FBR after successful submission. Format: {NTN}DI{timestamp} e.g. '7000007DI1747119701593'. Printed as QR code on receipt.", max_length=100, verbose_name='FBR Invoice Number')),
                ('fbr_scenario_id', models.CharField(blank=True, help_text="The sandbox scenario code used for this invoice (e.g. 'SN001'). Determined at submission time based on customer registration type and product sale types.", max_length=10, verbose_name='FBR Scenario ID')),
                ('fbr_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='FBR Submitted At')),
                ('fbr_error_code', models.CharField(blank=True, help_text="Error code from FBR response if submission failed (e.g. '0046').", max_length=10, verbose_name='FBR Error Code')),
                ('fbr_error_message', models.TextField(blank=True, help_text='Full error message from FBR if submission failed.', verbose_name='FBR Error Message')),
                ('fbr_qr_code', models.TextField(blank=True, help_text='QR code content for printing on receipt. Version 2.0 (25×25), 1.0 × 1.0 inch as per PRAL spec.', verbose_name='FBR QR Code Data')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('completed_at', models.DateTimeField(blank=True, help_text="When the sale was finalised. Maps to 'invoiceDate' in FBR JSON.", null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cash_session', models.ForeignKey(blank=True, help_text="The open cash session this sale belongs to. NULL if company doesn't use cash sessions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.cashsession', verbose_name='Cash Session')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Cashier / Created By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.company', verbose_name='Company')),
                ('customer', models.ForeignKey(help_text='Required. Use the walk-in record for anonymous cash sales. For FBR registered buyer scenarios, customer must have a valid NTN.', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.customer', verbose_name='Customer')),
                ('original_sale', models.ForeignKey(blank=True, help_text="Maps to 'invoiceRefNo' in FBR JSON. Required when sale_type is Debit Note or Credit Note.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_debit_notes', to='pos.sale', verbose_name='Original Sale (for Debit/Credit Notes)')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text="Copied from product.name at sale time. Maps to 'productDescription' in FBR JSON.", max_length=255, verbose_name='Product Name (snapshot)')),
                ('hs_code', models.CharField(blank=True, help_text="Copied from product.hs_code at sale time. Maps to 'hsCode' in FBR JSON.", max_length=20, verbose_name='HS Code (snapshot)')),
                ('unit_of_measure', models.CharField(help_text="Copied from product.unit_of_measure at sale time. Maps to 'uoM' in FBR JSON.", max_length=50, verbose_name='Unit of Measure (snapshot)')),
                ('fbr_sale_type', models.CharField(help_text="Copied from product.fbr_sale_type at sale time. Maps to 'saleType' in FBR JSON.", max_length=80, verbose_name='FBR Sale Type (snapshot)')),
                ('tax_rate_percent', models.CharField(help_text="Copied from product.tax_rate_percent at sale time. Maps to 'rate' in FBR JSON.", max_length=10, verbose_name='Tax Rate (snapshot)')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Copied from product.selling_price at sale time.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price (excl. tax)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'discount' in FBR JSON.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Amount')),
                ('value_excl_tax', models.DecimalField(decimal_places=2, default=0, help_text="unit_price × quantity. Maps to 'valueSalesExcludingST' in FBR JSON.", max_digits=14, verbose_name='Value excl. Tax')),
                ('sales_tax_applicable', models.DecimalField(decimal_places=2, default=0, help_text="value_excl_tax × tax_rate. Maps to 'salesTaxApplicable' in FBR JSON.", max_digits=14, verbose_name='Sales Tax Applicable')),
                ('sales_tax_withheld', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'salesTaxWithheldAtSource' in FBR JSON.", max_digits=12, verbose_name='Sales Tax Withheld at Source')),
                ('further_tax', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'furtherTax' in FBR JSON.", max_digits=12, verbose_name='Further Tax')),
                ('extra_tax', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'extraTax' in FBR JSON.", max_digits=12, verbose_name='Extra Tax')),
                ('fed_payable', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'fedPayable' in FBR JSON.", max_digits=12, verbose_name='FED Payable')),
                ('fixed_retail_price', models.DecimalField(decimal_places=2, default=0, help_text="Maps to 'fixedNotifiedValueOrRetailPrice' in FBR JSON.", max_digits=12, verbose_name='Fixed / Notified Retail Price')),
                ('sro_schedule_no', models.CharField(blank=True, help_text="Maps to 'sroScheduleNo' in FBR JSON.", max_length=50, verbose_name='SRO Schedule No.')),
                ('sro_item_serial_no', models.CharField(blank=True, help_text="Maps to 'sroItemSerialNo' in FBR JSON.", max_length=20, verbose_name='SRO Item Serial No.')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text="value_excl_tax + sales_tax + further_tax + fed − discount. Maps to 'totalValues'.", max_digits=14, verbose_name='Line Total (incl. all taxes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='pos.product', verbose_name='Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale Line',
                'verbose_name_plural': 'Sale Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Debit/Credit)'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('cheque_number', models.CharField(blank=True, max_length=50, verbose_name='Cheque Number')),
                ('cheque_bank', models.CharField(blank=True, max_length=100, verbose_name='Cheque Bank')),
                ('cheque_date', models.DateField(blank=True, null=True, verbose_name='Cheque Date')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank Transfer Reference')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Card Last 4 Digits')),
                ('card_type', models.CharField(blank=True, help_text='e.g. Visa, Mastercard, UnionPay', max_length=20, verbose_name='Card Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Sale Payment',
                'verbose_name_plural': 'Sale Payments',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['company', 'status'], name='cashsession_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['cashier'], name='cashsession_cashier_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('company', 'cashier'), name='unique_open_session_per_cashier'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'status'], name='sale_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'completed_at'], name='sale_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['fbr_submission_status'], name='sale_fbr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['fbr_invoice_number'], name='sale_fbr_inv_no_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='sale_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale'], name='salepayment_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['payment_method'], name='salepayment_method_idx'),
        ),
    ]
