# Generated by Django 6.0.6 on 2026-06-23 08:11

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_cashsession_sale_saleline_salepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.product_image_upload_path, verbose_name='Product Image'),
        ),
    ]
