# Generated by Django 6.0.6 on 2026-06-23 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo'),
        ('pos', '0004_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(help_text='Auto-generated. Format: RET-YYYY-NNNNNN', max_length=50, unique=True, verbose_name='Return Number')),
                ('return_type', models.CharField(choices=[('full', 'Full Return'), ('partial', 'Partial Return')], max_length=10, verbose_name='Return Type')),
                ('reason', models.CharField(choices=[('defective', 'Defective / Damaged Product'), ('wrong_item', 'Wrong Item Delivered'), ('customer_changed', 'Customer Changed Mind'), ('overcharged', 'Overcharged'), ('expired', 'Expired Product'), ('other', 'Other')], default='other', max_length=20, verbose_name='Return Reason')),
                ('reason_notes', models.TextField(blank=True, help_text="Required when reason is 'Other'.", verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all returned line totals including tax.', max_digits=14, verbose_name='Total Return Amount')),
                ('total_return_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Tax Returned')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cash refunded to customer. Equals total_return_amount.', max_digits=14, verbose_name='Refund Amount')),
                ('refund_paid', models.BooleanField(default=False, help_text='True when cash has been physically returned to customer.', verbose_name='Refund Paid')),
                ('refund_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Refund Paid At')),
                ('fbr_eligible', models.BooleanField(default=True, help_text='False if original invoice is older than 72 hours or has been reported in a submitted return. If False, return is processed internally but no credit note sent to FBR.', verbose_name='FBR Credit Note Eligible')),
                ('fbr_eligibility_reason', models.CharField(blank=True, help_text='Reason why credit note cannot be submitted to FBR.', max_length=255, verbose_name='FBR Ineligibility Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='companies.company', verbose_name='Company')),
                ('credit_note_sale', models.OneToOneField(blank=True, help_text='Auto-created Credit Note Sale linked to this return. Submitted to FBR as a Credit Note invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_credit_note', to='pos.sale', verbose_name='Credit Note Sale')),
                ('original_sale', models.ForeignKey(help_text='The completed sale this return is against. Must have a valid FBR invoice number for credit note submission.', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.sale', verbose_name='Original Sale')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Sale Return',
                'verbose_name_plural': 'Sale Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name (snapshot)')),
                ('quantity_returned', models.DecimalField(decimal_places=3, help_text='Cannot exceed original line quantity.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity Returned')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Copied from original line.', max_digits=12, verbose_name='Unit Price')),
                ('tax_rate_percent', models.CharField(max_length=10, verbose_name='Tax Rate')),
                ('return_value_excl_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Return Value excl. Tax')),
                ('return_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Return Tax')),
                ('return_line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Return Line Total')),
                ('stock_restored', models.BooleanField(default=False, verbose_name='Stock Restored')),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='pos.saleline', verbose_name='Original Sale Line')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.salereturn', verbose_name='Sale Return')),
            ],
            options={
                'verbose_name': 'Sale Return Line',
                'verbose_name_plural': 'Sale Return Lines',
            },
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['company', 'status'], name='return_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['original_sale'], name='return_original_sale_idx'),
        ),
    ]
