# Generated by Django 6.0.6 on 2026-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_salereturn_salereturnline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_a4_url',
            field=models.URLField(blank=True, help_text='S3 URL of generated A4 invoice PDF. Auto-populated on first invoice request.', verbose_name='A4 Invoice URL'),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last receipt generation.', null=True, verbose_name='Receipt Generated At'),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_thermal_url',
            field=models.URLField(blank=True, help_text='S3 URL of generated 80mm thermal receipt PDF. Auto-populated on first receipt request. Empty until first generated.', verbose_name='Thermal Receipt URL'),
        ),
    ]
