# Generated by Django 6.0.6 on 2026-06-25 02:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo'),
        ('pos', '0006_sale_receipt_a4_url_sale_receipt_generated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_number', models.CharField(help_text='Auto-generated. Format: DN-YYYY-NNNNNN', max_length=50, unique=True, verbose_name='Debit Note Number')),
                ('reason', models.CharField(choices=[('forgotten_items', 'Forgotten Items — items missed on original invoice'), ('price_correction', 'Price Correction — item was undercharged'), ('service_charge', 'Additional Service Charge'), ('other', 'Other')], default='forgotten_items', max_length=20, verbose_name='Reason')),
                ('reason_notes', models.TextField(blank=True, help_text="Required when reason is 'Other'. Shown on FBR debit note.", verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed & Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=15, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all debit note lines including tax.', max_digits=14, verbose_name='Total Amount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Tax')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='cash', help_text='How customer paid the debit note amount.', max_length=20, verbose_name='Payment Method')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount Paid')),
                ('change_given', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Change Given')),
                ('payment_collected', models.BooleanField(default=False, help_text='True when customer has physically paid the debit note amount.', verbose_name='Payment Collected')),
                ('payment_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Collected At')),
                ('fbr_eligible', models.BooleanField(default=True, help_text='False if original invoice is older than 72 hours. If False, debit note is processed internally only.', verbose_name='FBR Debit Note Eligible')),
                ('fbr_eligibility_reason', models.CharField(blank=True, max_length=255, verbose_name='FBR Ineligibility Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='companies.company', verbose_name='Company')),
                ('debit_note_sale', models.OneToOneField(blank=True, help_text='Auto-created Debit Note Sale. Submitted to FBR as a Debit Note invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_record', to='pos.sale', verbose_name='Debit Note Sale')),
                ('original_sale', models.ForeignKey(help_text='The completed sale this debit note is against. Must have a valid FBR invoice number.', on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='pos.sale', verbose_name='Original Sale')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_debit_notes', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Product name for forgotten items, correction detail for price corrections, charge description for service charges.', max_length=255, verbose_name='Description')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='HS Code')),
                ('unit_of_measure', models.CharField(default='Numbers, pieces, units', max_length=50, verbose_name='Unit of Measure')),
                ('fbr_sale_type', models.CharField(default='Goods at standard rate (default)', max_length=80, verbose_name='FBR Sale Type')),
                ('tax_rate_percent', models.CharField(default='18%', max_length=10, verbose_name='Tax Rate')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price (excl. tax)')),
                ('value_excl_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Value excl. Tax')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Line Total (incl. tax)')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.debitnote', verbose_name='Debit Note')),
                ('original_line', models.ForeignKey(blank=True, help_text='For price corrections only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_lines', to='pos.saleline', verbose_name='Original Sale Line')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_lines', to='pos.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Debit Note Line',
                'verbose_name_plural': 'Debit Note Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['company', 'status'], name='debitnote_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='debitnote',
            index=models.Index(fields=['original_sale'], name='debitnote_original_sale_idx'),
        ),
    ]
