# Generated by Django 6.0.6 on 2026-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_debitnote_debitnoteline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('Numbers, pieces, units', 'Numbers / Pieces / Units'), ('1000 kWh', 'Thousand Kilowatt Hours'), ('40 KG', '40 Kilogram bag'), ('Bag', 'Bag'), ('Barrels', 'Barrels'), ('Bill of Lading', 'Bill of Lading'), ('Bottle', 'Bottle'), ('Box', 'Box'), ('Bundle', 'Bundle'), ('Carat', 'Carat'), ('Carton', 'Carton'), ('Case', 'Case'), ('Cubic Metre', 'Cubic Metre'), ('Dozen', 'Dozen'), ('Drum', 'Drum'), ('Foot', 'Foot'), ('Gallon', 'Gallon'), ('Gram', 'Gram'), ('Inch', 'Inch'), ('KG', 'Kilogram (KG)'), ('KWH', 'Kilowatt Hour (KWH)'), ('Litre', 'Litre'), ('Mega Watt (MW)', 'Mega Watt (MW)'), ('Metre', 'Metre'), ('Metric Ton', 'Metric Ton'), ('Million BTU (MMBTU)', 'Million BTU (MMBTU)'), ('Pack', 'Pack / Packet'), ('Pair', 'Pair'), ('Pallet', 'Pallet'), ('Piece', 'Piece'), ('Roll', 'Roll'), ('Set', 'Set'), ('Sheet', 'Sheet'), ('Square Foot', 'Square Foot'), ('Square Metre', 'Square Metre'), ('Ton', 'Ton'), ('Tube', 'Tube'), ('Yard', 'Yard')], default='Numbers, pieces, units', help_text="Maps to 'uoM' in FBR invoice JSON. Must match FBR reference values from /pdi/v1/uom.", max_length=50, verbose_name='Unit of Measure (UoM)'),
        ),
    ]
