# Generated by Django 6.0.6 on 2026-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='HS Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('default_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Default Rate')),
                ('uom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Unit of Measure')),
            ],
            options={
                'verbose_name': 'HS Code',
                'verbose_name_plural': 'HS Codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='pos_hscode_code_160af8_idx')],
            },
        ),
    ]
