# Generated by Django 6.0.6 on 2026-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CNIC'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit Limit (Rs)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ntn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NTN'),
        ),
    ]
