# Generated by Django 6.0.6 on 2026-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_customer_cnic_customer_credit_limit_customer_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='fbr_submission_status',
            field=models.CharField(choices=[('pending', 'Pending — not yet submitted to FBR'), ('validated', 'Validated (Dry-run)'), ('success', 'Submitted & Validated by FBR'), ('failed', 'Submission Failed'), ('skipped', 'Skipped — FBR DI not enabled for this company')], default='pending', max_length=10, verbose_name='FBR Submission Status'),
        ),
    ]
