# Generated by Django 6.0.6 on 2026-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_sale_fbr_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ntn_cnic',
            field=models.CharField(blank=True, help_text="National Tax Number (7 or 9 digits) for registered businesses, or CNIC (13 digits) for individuals. REQUIRED for FBR registered buyer scenarios (SN001, SN005). Maps to 'buyerNTNCNIC' in FBR invoice JSON.", max_length=50, verbose_name='NTN / CNIC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_type',
            field=models.CharField(choices=[('Registered', 'Registered (NTN holder)'), ('Unregistered', 'Unregistered')], default='Unregistered', help_text="Registered = NTN holder who can claim input tax credit. Unregistered = individual or non-registered business. Maps to 'buyerRegistrationType' in FBR invoice JSON.", max_length=50, verbose_name='Registration Type'),
        ),
    ]
