# Generated by Django 6.0.6 on 2026-06-30 17:10

import config.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auditlog'),
        ('pos', '0013_alter_customer_ntn_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Debit/Credit)'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('raast', 'Raast')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.CreateModel(
            name='CompanyPaymentMethodSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cash_enabled', models.BooleanField(default=True)),
                ('is_card_enabled', models.BooleanField(default=False)),
                ('is_easypaisa_enabled', models.BooleanField(default=False)),
                ('is_jazzcash_enabled', models.BooleanField(default=False)),
                ('is_raast_enabled', models.BooleanField(default=False)),
                ('is_bank_transfer_enabled', models.BooleanField(default=False)),
                ('is_cheque_enabled', models.BooleanField(default=False)),
                ('easypaisa_merchant_id', models.CharField(blank=True, max_length=100)),
                ('easypaisa_qr_image', models.ImageField(blank=True, null=True, upload_to=config.storage_backends.payment_qr_upload_path)),
                ('jazzcash_merchant_id', models.CharField(blank=True, max_length=100)),
                ('jazzcash_qr_image', models.ImageField(blank=True, null=True, upload_to=config.storage_backends.payment_qr_upload_path)),
                ('raast_iban', models.CharField(blank=True, max_length=100)),
                ('raast_qr_image', models.ImageField(blank=True, null=True, upload_to=config.storage_backends.payment_qr_upload_path)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('bank_iban', models.CharField(blank=True, max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
