# Generated by Django 6.0.6 on 2026-06-21 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('ntn', models.CharField(help_text='National Tax Number — 7 digits (e.g. 1234567)', max_length=15, unique=True, verbose_name='NTN')),
                ('strn', models.CharField(blank=True, help_text='Sales Tax Registration Number — 13 digits', max_length=17, null=True, unique=True, verbose_name='STRN')),
                ('owner_cnic', models.CharField(help_text='Format: 00000-0000000-0 (13 digits with dashes)', max_length=15, verbose_name='Owner CNIC')),
                ('business_mode', models.CharField(choices=[('pos_only', 'POS Only'), ('di_only', 'Digital Invoicing Only'), ('both', 'POS + Digital Invoicing')], default='pos_only', help_text='Which product(s) this company has licensed. Does NOT auto-set any modules — admin configures modules independently.', max_length=20, verbose_name='Business Mode')),
                ('fbr_business_nature', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('importer', 'Importer'), ('exporter', 'Exporter'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('other', 'Other')], max_length=30), blank=True, default=list, help_text='Multiple values allowed. Drives sandbox scenario assignment in IRIS.', verbose_name='FBR Business Nature')),
                ('fbr_sector', models.CharField(blank=True, choices=[('potassium_chloride', 'Potassium Chloride'), ('cement_concrete', 'Cement & Concrete Block'), ('mobile_wholesale', 'Mobile Wholesale/Retail'), ('pharmaceuticals', 'Pharmaceuticals'), ('cng_station', 'CNG Station'), ('automobiles', 'Automobiles'), ('services', 'Services'), ('gas_distribution', 'Gas Distribution'), ('electricity', 'Electricity Distribution'), ('petroleum', 'Petroleum'), ('telecom', 'Telecom'), ('textile', 'Textile'), ('fmcg', 'FMCG'), ('steel', 'Steel'), ('all_other', 'All Other Sectors')], help_text='Exactly one sector. Combined with Business Nature to determine eligible scenarios.', max_length=30, null=True, verbose_name='FBR Sector')),
                ('vertical', models.CharField(choices=[('grocery', 'Grocery Store'), ('general_store', 'General Store'), ('restaurant', 'Restaurant / F&B'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('clothing', 'Clothing / Apparel'), ('wholesale', 'Wholesale'), ('other', 'Other')], default='general_store', help_text='Internal classification that controls which POS features/UI this company sees. Independent of FBR Sector.', max_length=30, verbose_name='Business Vertical')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('address', models.TextField(help_text='Full address in a single field (city, province, postal code).', verbose_name='Business Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Business Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Business Email')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('subscription_plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='trial', max_length=20, verbose_name='Subscription Plan')),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20, verbose_name='Subscription Status')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='Subscription Start Date')),
                ('subscription_expiry_date', models.DateField(blank=True, null=True, verbose_name='Subscription Expiry Date')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Next Billing Date')),
                ('module_sales_invoicing', models.BooleanField(default=False, verbose_name='Sales Invoicing')),
                ('module_fbr_di', models.BooleanField(default=False, verbose_name='FBR Digital Invoicing')),
                ('module_customer_db', models.BooleanField(default=True, verbose_name='Customer Database')),
                ('module_fbr_registered_buyer', models.BooleanField(default=False, verbose_name='FBR Registered Buyer Scenarios')),
                ('module_returns', models.BooleanField(default=False, verbose_name='Returns & Debit/Credit Notes')),
                ('module_fbr_amendments', models.BooleanField(default=False, verbose_name='Manual FBR Amendments')),
                ('module_cheque_bank_transfer', models.BooleanField(default=False, verbose_name='Cheque & Bank Transfer')),
                ('module_customer_display', models.BooleanField(default=False, verbose_name='Customer-Facing Display')),
                ('module_hardware_integration', models.BooleanField(default=False, verbose_name='Hardware Integration')),
                ('module_inventory', models.BooleanField(default=False, verbose_name='Inventory Tracking')),
                ('module_warehousing', models.BooleanField(default=False, verbose_name='Warehousing')),
                ('module_multi_location', models.BooleanField(default=False, help_text='Reserved for future use. Currently disabled in all business logic.', verbose_name='Multi-Location / Multi-Branch')),
                ('module_restaurant_fnb', models.BooleanField(default=False, verbose_name='Restaurant F&B')),
                ('module_dine_in', models.BooleanField(default=False, verbose_name='Dine-In')),
                ('module_takeaway', models.BooleanField(default=False, verbose_name='Takeaway')),
                ('module_delivery', models.BooleanField(default=False, verbose_name='Delivery')),
                ('module_table_floor_map', models.BooleanField(default=False, verbose_name='Table & Floor Map')),
                ('module_kitchen_display', models.BooleanField(default=False, verbose_name='Kitchen Display / KDS')),
                ('module_basic_reports', models.BooleanField(default=True, verbose_name='Basic Reports')),
                ('module_advanced_reports', models.BooleanField(default=False, verbose_name='Advanced Reports')),
                ('module_audit_logs', models.BooleanField(default=False, verbose_name='Audit Logs')),
                ('fbr_sandbox_token', models.TextField(blank=True, help_text='Issued by IRIS after IP whitelisting is accepted. Used for test invoice submission.', verbose_name='FBR Sandbox Token')),
                ('fbr_production_token', models.TextField(blank=True, help_text='Issued automatically by IRIS once all sandbox scenarios are cleared. Required before any live invoice can be submitted.', verbose_name='FBR Production Token')),
                ('fbr_assigned_scenarios', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text="List of scenario codes this tenant must clear in sandbox (e.g. ['SN001', 'SN002', 'SN005']). Copied manually from IRIS — FBR does not expose an API for this. Admin can override the platform's auto-suggested default.", verbose_name='FBR Assigned Sandbox Scenarios')),
                ('fbr_test_buyer_ntn', models.CharField(blank=True, help_text="Required only if this tenant's scenarios include SN001 or SN005 (registered buyer scenarios). PRAL's own test NTN is NOT pre-registered.", max_length=15, verbose_name='FBR Test Buyer NTN')),
                ('fbr_sandbox_complete', models.BooleanField(default=False, help_text='Flipped to True once all assigned scenarios are cleared and a production token is issued.', verbose_name='Sandbox Testing Complete')),
                ('fbr_ip_1', models.GenericIPAddressField(blank=True, null=True, verbose_name='Whitelisted IP 1')),
                ('fbr_ip_2', models.GenericIPAddressField(blank=True, null=True, verbose_name='Whitelisted IP 2')),
                ('fbr_ip_3', models.GenericIPAddressField(blank=True, null=True, verbose_name='Whitelisted IP 3')),
                ('fbr_crm_user_id', models.EmailField(blank=True, help_text='Email registered as Technical Contact Person in IRIS Technical Details.', max_length=254, verbose_name='FBR CRM User ID (Email)')),
                ('account_manager', models.CharField(blank=True, help_text='Name of the internal staff member responsible for this account.', max_length=100, verbose_name='Account Manager')),
                ('internal_notes', models.TextField(blank=True, help_text='Visible only to Admin/Admin Staff. Never shown in the POS or client-facing UI.', verbose_name='Internal Notes')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Free-form labels for filtering/searching companies in the admin app.', verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive companies cannot log into the POS. Deactivate instead of deleting — records are never hard-deleted.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ntn'], name='company_ntn_idx'), models.Index(fields=['is_active'], name='company_active_idx'), models.Index(fields=['subscription_status'], name='company_sub_status_idx')],
            },
        ),
    ]
