# Generated by Django 6.0.6 on 2026-06-22 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fbr_assigned_scenarios',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_delivery',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_dine_in',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_fbr_registered_buyer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_kitchen_display',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_multi_location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_sales_invoicing',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_table_floor_map',
        ),
        migrations.RemoveField(
            model_name='company',
            name='module_takeaway',
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn001',
            field=models.BooleanField(default=False, verbose_name='SN001 · Standard Rate — Registered Buyer'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn002',
            field=models.BooleanField(default=False, verbose_name='SN002 · Standard Rate — Unregistered Buyer'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn003',
            field=models.BooleanField(default=False, verbose_name='SN003 · Steel Melted'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn004',
            field=models.BooleanField(default=False, verbose_name='SN004 · Steel Scrap by Ship Breaker'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn005',
            field=models.BooleanField(default=False, verbose_name='SN005 · Reduced Rate — Registered Buyer'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn006',
            field=models.BooleanField(default=False, verbose_name='SN006 · Exempted Goods'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn007',
            field=models.BooleanField(default=False, verbose_name='SN007 · Zero Rated Goods'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn008',
            field=models.BooleanField(default=False, verbose_name='SN008 · Third Schedule Goods'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn009',
            field=models.BooleanField(default=False, verbose_name='SN009 · Purchase from Cotton Grower'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn010',
            field=models.BooleanField(default=False, verbose_name='SN010 · Telecom Services by Mobile Operators'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn011',
            field=models.BooleanField(default=False, verbose_name='SN011 · Steel via Toll Manufacturing'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn012',
            field=models.BooleanField(default=False, verbose_name='SN012 · Petroleum Products'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn013',
            field=models.BooleanField(default=False, verbose_name='SN013 · Electricity to Retailers'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn014',
            field=models.BooleanField(default=False, verbose_name='SN014 · Gas to CNG Stations'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn015',
            field=models.BooleanField(default=False, verbose_name='SN015 · Mobile Phones'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn016',
            field=models.BooleanField(default=False, verbose_name='SN016 · Processing / Conversion of Goods'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn017',
            field=models.BooleanField(default=False, verbose_name='SN017 · Goods (FED in ST Mode)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn018',
            field=models.BooleanField(default=False, verbose_name='SN018 · Services (FED in ST Mode)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn019',
            field=models.BooleanField(default=False, verbose_name='SN019 · Services (ICT Ordinance)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn020',
            field=models.BooleanField(default=False, verbose_name='SN020 · Electric Vehicles'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn021',
            field=models.BooleanField(default=False, verbose_name='SN021 · Cement / Concrete Block'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn022',
            field=models.BooleanField(default=False, verbose_name='SN022 · Potassium Chloride'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn023',
            field=models.BooleanField(default=False, verbose_name='SN023 · SNNG Sale'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn024',
            field=models.BooleanField(default=False, verbose_name='SN024 · Goods per SC004'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn025',
            field=models.BooleanField(default=False, verbose_name='SN025 · Goods per SRO2971'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn026',
            field=models.BooleanField(default=False, verbose_name='SN026 · Standard Rate — End Consumer (Retailer)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn027',
            field=models.BooleanField(default=False, verbose_name='SN027 · Third Schedule — End Consumer (Retailer)'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_scenario_sn028',
            field=models.BooleanField(default=False, verbose_name='SN028 · Reduced Rate — End Consumer (Retailer)'),
        ),
        migrations.AddField(
            model_name='company',
            name='module_debit_credit_notes',
            field=models.BooleanField(default=False, help_text='Issue follow-up notes against existing FBR-validated invoices for forgotten items or amendments.', verbose_name='Debit / Credit Notes'),
        ),
        migrations.AddField(
            model_name='company',
            name='module_invoices',
            field=models.BooleanField(default=True, help_text='Create, list, and manage invoices. FORCED — cannot be disabled. This is the core product.', verbose_name='Invoices'),
        ),
        migrations.AddField(
            model_name='company',
            name='module_multi_branch',
            field=models.BooleanField(default=False, help_text='Multiple physical locations. When disabled the tenant operates from a single implicit branch. Reserved for future use — not wired to branch-creation logic yet.', verbose_name='Multi-Branch'),
        ),
        migrations.AddField(
            model_name='company',
            name='module_terminals_cash_sessions',
            field=models.BooleanField(default=False, help_text='POS terminal registration and cashier shift open/close flow.', verbose_name='Terminals & Cash Sessions'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(help_text='Full address in a single field (street, city, province, postal code).', verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_business_nature',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('importer', 'Importer'), ('exporter', 'Exporter'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('other', 'Other')], max_length=30), blank=True, default=list, help_text='One or more FBR-defined business natures. Required before submitting invoices to PRAL.', verbose_name='FBR Business Nature'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_crm_user_id',
            field=models.EmailField(blank=True, help_text='Email registered as Technical Contact Person in IRIS Technical Details. Used to log into dicrm.pral.com.pk', max_length=254, verbose_name='FBR CRM User ID (Email)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_production_token',
            field=models.TextField(blank=True, help_text='Issued automatically by IRIS once ALL assigned sandbox scenarios are cleared. Required before any live invoice can be submitted.', verbose_name='FBR Production Token'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_sandbox_complete',
            field=models.BooleanField(default=False, help_text='Set to True automatically once all assigned scenarios are cleared and a production token is issued.', verbose_name='Sandbox Testing Complete'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_sector',
            field=models.CharField(blank=True, choices=[('potassium_chlorate', 'Potassium Chlorate'), ('cement_concrete', 'Cement or Concrete Blocks'), ('mobile', 'Mobile'), ('wholesale_retails', 'Wholesale / Retails'), ('pharmaceuticals', 'Pharmaceuticals'), ('cng_stations', 'CNG Stations'), ('automobile', 'Automobile'), ('services', 'Services'), ('gas_distribution', 'Gas Distribution'), ('electricity', 'Electricity Distribution'), ('petroleum', 'Petroleum'), ('telecom', 'Telecom'), ('textile', 'Textile'), ('fmcg', 'FMCG'), ('steel', 'Steel'), ('all_other', 'All Other Sectors')], help_text='Exactly one sector. Combined with Business Nature to determine eligible sandbox scenarios inside IRIS.', max_length=30, null=True, verbose_name='FBR Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fbr_test_buyer_ntn',
            field=models.CharField(blank=True, help_text="Required only if this tenant's assigned scenarios include SN001 or SN005 (registered buyer scenarios). PRAL's own test NTN is NOT pre-registered — enter the actual test NTN here.", max_length=15, verbose_name='FBR Test Buyer NTN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Visible only to Admin/Admin Staff. Never shown in POS or client UI.', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_advanced_reports',
            field=models.BooleanField(default=False, help_text='Scheduled reports, period comparisons, exports.', verbose_name='Reports — Advanced'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_audit_logs',
            field=models.BooleanField(default=False, help_text='Six-year-retention audit trail viewer.', verbose_name='Audit Log'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_basic_reports',
            field=models.BooleanField(default=True, help_text="Daily summary, today's sales, simple lookups.", verbose_name='Reports — Basic'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_cheque_bank_transfer',
            field=models.BooleanField(default=False, help_text='Beyond cash and card — cheques, bank refs, wallet payment tracking.', verbose_name='Cheques + Bank Transfers'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_customer_db',
            field=models.BooleanField(default=True, help_text='Customer database with NTN/CNIC. FORCED — FBR registered-buyer scenarios require a customer record with NTN.', verbose_name='Customers'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_customer_display',
            field=models.BooleanField(default=False, help_text='The second-monitor display showing the running cart and post-sale thank-you.', verbose_name='Customer-Facing Display'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_fbr_amendments',
            field=models.BooleanField(default=False, help_text='Phase 4 manual-amendment workflow including Annexure-C linkage.', verbose_name='Manual FBR Amendments'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_fbr_di',
            field=models.BooleanField(default=True, help_text='Submit invoices to PRAL and store FBR tokens. FORCED — FBR submission is the primary value of the platform.', verbose_name='FBR Digital Invoicing'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_hardware_integration',
            field=models.BooleanField(default=False, help_text='Thermal printer, barcode scanner, cash drawer kick.', verbose_name='Hardware Integrations'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_inventory',
            field=models.BooleanField(default=False, help_text='Stock levels, movements, adjustments, transfers, stock audits.', verbose_name='Inventory Tracking'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_restaurant_fnb',
            field=models.BooleanField(default=False, help_text='Single toggle that gates ALL restaurant features: dine-in / takeaway / delivery orders, tables + floor map, menu modifiers (add-ons / sizes), kitchen tickets (KDS) + KDOC. Gates the restaurant API; pair with the restaurant vertical to surface the UI.', verbose_name='Restaurant / F&B'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_returns',
            field=models.BooleanField(default=False, help_text='Customer returns workflow.', verbose_name='Returns'),
        ),
        migrations.AlterField(
            model_name='company',
            name='module_warehousing',
            field=models.BooleanField(default=False, help_text='Per-warehouse stock for Digital-Invoicing tenants: godowns under a branch, opening balance + stock-in per warehouse, and warehouse-keyed sale deduction.', verbose_name='Warehouses (Digital Invoicing)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="Free-form labels for filtering companies in the admin app (e.g. 'vip', 'cash-only').", verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vertical',
            field=models.CharField(choices=[('grocery', 'Grocery Store'), ('general_store', 'General Store'), ('restaurant', 'Restaurant / F&B'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('clothing', 'Clothing / Apparel'), ('wholesale', 'Wholesale'), ('other', 'Other')], default='general_store', help_text='Controls which POS features/UI this company sees. Independent of FBR Sector.', max_length=30, verbose_name='Business Vertical'),
        ),
    ]
