# Generated by Django 6.0.6 on 2026-06-23 08:11

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_fbr_assigned_scenarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=config.storage_backends.company_logo_upload_path, verbose_name='Company Logo'),
        ),
    ]
