# Generated by Django 6.0.6 on 2026-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fbr_production_endpoint',
            field=models.URLField(blank=True, default='https://gw.fbr.gov.pk', verbose_name='FBR Production Endpoint'),
        ),
        migrations.AddField(
            model_name='company',
            name='fbr_sandbox_endpoint',
            field=models.URLField(blank=True, default='https://esp.pral.com.pk', verbose_name='FBR Sandbox Endpoint'),
        ),
    ]
