# Generated by Django 6.0.6 on 2026-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_fbr_production_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ntn',
            field=models.CharField(help_text='National Tax Number or CNIC', max_length=30, unique=True, verbose_name='NTN'),
        ),
    ]
