# Generated by Django 6.0.6 on 2026-06-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_ntn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(help_text="Email of the user or '(system)'", max_length=255)),
                ('entity_type', models.CharField(help_text='e.g. invoice, product, customer, fbr_token', max_length=50)),
                ('entity_id', models.CharField(help_text='UUID or ID of the entity', max_length=100)),
                ('action', models.CharField(help_text='e.g. create, update, delete, fbr_validated, resubmit', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='companies_a_company_796c49_idx'), models.Index(fields=['entity_type', 'entity_id'], name='companies_a_entity__f39fcb_idx')],
            },
        ),
    ]
