# Generated by Django 6.0.6 on 2026-06-24 06:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Trial, Starter, Pro, Premium, Enterprise', max_length=100, unique=True, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, help_text='Shown to admin when assigning plan to a company.', verbose_name='Description')),
                ('is_trial', models.BooleanField(default=False, help_text='Trial plans are given free for a limited period. Each company can only use a trial plan once.', verbose_name='Is Trial Plan')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be assigned to new companies. Existing subscriptions on this plan are not affected.', verbose_name='Active')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 for free/trial plans.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price Per Month (Rs.)')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='How many days this plan lasts. Trial plans typically 14 days, paid plans 30 days.', verbose_name='Duration (Days)')),
                ('max_products', models.PositiveIntegerField(default=100, help_text='Maximum number of active products. 0 = unlimited.', verbose_name='Max Products')),
                ('max_users', models.PositiveIntegerField(default=3, help_text='Maximum number of staff users (Manager, Cashier, Salesperson). Does not count the Owner. 0 = unlimited.', verbose_name='Max Staff Users')),
                ('max_customers', models.PositiveIntegerField(default=500, help_text='Maximum number of customer records. 0 = unlimited.', verbose_name='Max Customers')),
                ('max_sales_per_month', models.PositiveIntegerField(default=0, help_text='Maximum completed sales per month. 0 = unlimited.', verbose_name='Max Sales Per Month')),
                ('max_categories', models.PositiveIntegerField(default=20, help_text='Maximum product categories. 0 = unlimited.', verbose_name='Max Categories')),
                ('includes_fbr_di', models.BooleanField(default=True, verbose_name='Includes FBR Digital Invoicing')),
                ('includes_inventory', models.BooleanField(default=False, verbose_name='Includes Inventory Tracking')),
                ('includes_warehousing', models.BooleanField(default=False, verbose_name='Includes Warehousing')),
                ('includes_advanced_reports', models.BooleanField(default=False, verbose_name='Includes Advanced Reports')),
                ('includes_audit_logs', models.BooleanField(default=False, verbose_name='Includes Audit Logs')),
                ('includes_hardware_integration', models.BooleanField(default=False, verbose_name='Includes Hardware Integration')),
                ('includes_restaurant_fnb', models.BooleanField(default=False, verbose_name='Includes Restaurant F&B')),
                ('includes_multi_branch', models.BooleanField(default=False, verbose_name='Includes Multi-Branch')),
                ('includes_debit_credit_notes', models.BooleanField(default=True, verbose_name='Includes Debit/Credit Notes')),
                ('includes_returns', models.BooleanField(default=True, verbose_name='Includes Returns')),
                ('includes_cheque_bank', models.BooleanField(default=False, verbose_name='Includes Cheque & Bank Transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Plan Assigned'), ('upgraded', 'Plan Upgraded'), ('downgraded', 'Plan Downgraded'), ('extended', 'Subscription Extended'), ('expired', 'Subscription Expired'), ('suspended', 'Account Suspended'), ('reactivated', 'Account Reactivated'), ('cancelled', 'Subscription Cancelled')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='companies.company')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('suspended', 'Suspended — Manual suspension by admin'), ('cancelled', 'Cancelled')], default='trial', max_length=15, verbose_name='Status')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('expiry_date', models.DateField(help_text="After this date the company's POS access is blocked.", verbose_name='Expiry Date')),
                ('extended_by_days', models.PositiveIntegerField(default=0, help_text='Total days manually added by admin extensions.', verbose_name='Extended By (Days)')),
                ('extension_notes', models.TextField(blank=True, help_text='Admin notes about why extension was granted.', verbose_name='Extension Notes')),
                ('expiry_warning_sent', models.BooleanField(default=False, verbose_name='7-Day Warning Email Sent')),
                ('expiry_warning_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Warning Sent At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company', verbose_name='Company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='sub_company_status_idx'), models.Index(fields=['expiry_date'], name='sub_expiry_date_idx'), models.Index(fields=['status'], name='sub_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trial'])), fields=('company',), name='unique_active_subscription_per_company')],
            },
        ),
    ]
