# Generated by Django 6.0.6 on 2026-06-29 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['sort_order', 'price_per_month'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='code',
            field=models.CharField(blank=True, help_text="Stable identifier (e.g. 'starter', 'pro', 'enterprise').", max_length=50, null=True, unique=True, verbose_name='Plan Code'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_per_year',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 for free/trial plans.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price Per Year (Rs.)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in lists.', verbose_name='Sort Order'),
        ),
    ]
