# Generated by Django 6.0.6 on 2026-06-21 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales_invoicing', 'Sales Invoicing'), ('fbr_di', 'FBR Digital Invoicing'), ('customer_db', 'Customer Database'), ('fbr_registered_buyer', 'FBR Registered Buyer'), ('returns', 'Returns & Debit/Credit Notes'), ('fbr_amendments', 'Manual FBR Amendments'), ('cheque_bank_transfer', 'Cheque & Bank Transfer'), ('customer_display', 'Customer-Facing Display'), ('hardware_integration', 'Hardware Integration'), ('inventory', 'Inventory Tracking'), ('warehousing', 'Warehousing'), ('multi_location', 'Multi-Location / Multi-Branch'), ('restaurant_fnb', 'Restaurant F&B'), ('dine_in', 'Dine-In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery'), ('table_floor_map', 'Table & Floor Map'), ('kitchen_display', 'Kitchen Display / KDS'), ('basic_reports', 'Basic Reports'), ('advanced_reports', 'Advanced Reports'), ('audit_logs', 'Audit Logs'), ('user_management', 'User Management'), ('company_management', 'Company Management')], help_text='The feature area this permission belongs to. Used for UI grouping.', max_length=40, verbose_name='Module')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export'), ('approve', 'Approve')], help_text='The atomic operation being granted.', max_length=10, verbose_name='Action')),
                ('codename', models.CharField(help_text="Machine-readable identifier used in code checks. Auto-built as '{module}.{action}', e.g. 'fbr_di.create'. Never shown in the UI.", max_length=60, unique=True, verbose_name='Codename')),
                ('label', models.CharField(help_text="Human-readable name shown in the permission UI, e.g. 'Create FBR Digital Invoice'.", max_length=100, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation shown as a tooltip in the permission panel.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive permissions are hidden from the UI and cannot be granted. Use this instead of deleting — deletion would break existing UserPermission rows.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'action'],
                'indexes': [models.Index(fields=['module'], name='perm_module_idx'), models.Index(fields=['codename'], name='perm_codename_idx')],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Granted At')),
                ('granted_by', models.ForeignKey(blank=True, help_text='The user who assigned this permission. NULL for auto-granted owner permissions (created by signal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permission_app.permission', verbose_name='Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_custom', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['user', 'permission__module', 'permission__action'],
                'indexes': [models.Index(fields=['user'], name='userperm_user_idx'), models.Index(fields=['permission'], name='userperm_perm_idx')],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
