name : pipeline
on :
    push :
        branches : ["main"]
jobs :
    test:
        runs-on: ubuntu-latest

        steps :
            - uses: actions/checkout@v4
            - run : pwd
            - run : ls -la
            - run : python --version
            - run : echo "completed the steps "
            - uses : actions/setup-python@v5
              with:
                python-version : "3.12"
            - name : install dependencies
              run : pip install -r requirements.txt
            - name : check python 
              run : python manage.py check


        



            
     

