name : pipeline
on :
    push :
        branches : ["main"]
jobs :
    test:
        runs-on: ubuntu-latest

        steps :
            - uses: actions/checkout@v4
            - run : pwd
            - run : ls -la
            - run : python --version
            - run : echo "completed the steps "
     

